Added calendar
js-tasks-ru/htmlcss-20220811_exisego pull request #11
Opened 2022-09-01 21:24 UTC by superiorange

2022-09-01 21:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-01 21:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-02 19:17 UTC, GSemikozov requested changes

2022-09-02 19:17 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    width: 36px;
через родителя мы уже определили что доступное пространство контейнера делится поровну, нет необходимости фиксировать размеры ячейки

2022-09-02 19:17 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    width: 36px;
по высоте и ширине

2022-09-02 20:05 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-02 22:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-05 15:12 UTC, GSemikozov approved these changes

2022-09-05 15:12 UTC, merged