Added radio
js-tasks-ru/htmlcss-20220811_exisego pull request #19
Opened 2022-09-07 09:20 UTC by superiorange

2022-09-07 09:20 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-07 15:54 UTC, GSemikozov requested changes

2022-09-07 15:54 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +    display: flex;
принципиально inline-flex

2022-09-07 21:11 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-08 15:45 UTC, GSemikozov approved these changes

2022-09-08 15:45 UTC, merged