Added styled accordion
js-tasks-ru/htmlcss-20220811_exisego pull request #4
Opened 2022-08-17 14:25 UTC by superiorange

2022-08-17 14:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-08-17 15:16 UTC, GSemikozov requested changes

2022-08-17 15:16 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter&display=swap');
шрифты подключаем в fonts.css

2022-08-17 15:16 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +@mixin inter-font() {
миксины будем использовать когда дойдем до препроцессоров

2022-08-17 15:16 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +p {
глобальные стили / сбросы стилей оформляем в глобальных файлах по типу main.css или normalize.css

2022-08-17 15:16 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
ширину лучше жестко не фиксировать, если это инлайн-блок, то пусть зависит от внутреннего содержимого

2022-08-17 15:16 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion {
на самом деле по структуре не совсем верно - это элемент блока .accordion__item, а .accordion - вмещает в себя все эти элементы

2022-08-17 15:16 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    font-weight: 400;
не хватает font-family

2022-08-17 15:16 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding-bottom: 24px;
здесь лучше задать все общие паддинги

2022-08-17 15:16 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-left: 32px;
если зададим выше общие паддинги на уровне родителя, то здесь этого делать не придется

2022-08-17 15:16 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item {
.accordion__content

2022-08-17 15:16 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-left: 32px;
удалим

2022-08-17 15:16 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 649px;
удалим

2022-08-17 15:16 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__summary, .accordion__item {
если зададим выше и универсальный селектор в main.css заменим на body - все будет ок

2022-08-18 10:10 UTC, superiorange commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
А если убрать инлайн-блок? Мне кажется, что он вообще лишний тут

2022-08-18 10:25 UTC, superiorange commented on 03-lection1/02-accordion/accordion.css
> +.accordion {
Не могу понять, какая именно должна быть структура в таком случае?
`<details class="accordion">
<summary class="accordion__summary"></summary>
<p class="accordion__content"></p>
`
вот так?

2022-08-18 17:26 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-08-18 17:27 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-08-22 08:05 UTC, GSemikozov requested changes

2022-08-22 08:05 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
фиксированную ширину убираем)

2022-08-22 08:05 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        <p class="accordion__content">
лучше div с таким классом, и уже внутри общего элемента добавлять `<p>`

2022-08-22 21:20 UTC, superiorange commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
и добавить блок-контейнер для ограничения ширины аккордеонов?

2022-08-30 14:25 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
можно и без него

2022-08-30 14:26 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion {
```
.accordion
.accordion__item (класс вешаем на details)
```

2022-08-30 14:26 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
нет необходимости

2022-09-01 15:23 UTC, GSemikozov requested changes

2022-09-01 15:23 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 0 400px;
удалим

2022-09-01 16:32 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-02 19:15 UTC, GSemikozov approved these changes

2022-09-02 19:15 UTC, merged