Added skeleton component
js-tasks-ru/htmlcss-20220811_exisego pull request #7
Opened 2022-08-31 14:26 UTC by superiorange

2022-08-31 14:27 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-08-31 21:06 UTC, GSemikozov requested changes

2022-08-31 21:06 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    margin: 0 400px;
ого) 
нет, на уровне блока марджины мы не задаем.

2022-08-31 21:06 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__header__avatar {
ошибка в написании класса - "элемент элемента". На самом деле в классах это просто плоская структура - .skeleton__avatar

2022-08-31 21:06 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__header__title {
.skeleton__title

2022-08-31 21:06 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__text-large {
а модификатор пишется так - .skeleton__text_large. Ниже тоже надо поправить

2022-09-01 15:24 UTC, GSemikozov approved these changes

2022-09-01 15:24 UTC, merged